// <auto-generated />
using System;
using Butcher.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Butcher.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903124709_AddUnitOfMeasureUniqueIndexes")]
    partial class AddUnitOfMeasureUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Butcher.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SaleMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sale_mode");

                    b.Property<int>("SaleUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_product_code");

                    b.HasIndex("SaleUnitId")
                        .HasDatabaseName("ix_product_sale_unit_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.ProductionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateOnly>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<string>("RawMaterialRef")
                        .HasColumnType("text")
                        .HasColumnName("raw_material_ref");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sale_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_production_batch");

                    b.HasIndex("BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_production_batch_batch_number");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_production_batch_created_by_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_batch_product_id");

                    b.ToTable("production_batch", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("SoldWeight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("sold_weight");

                    b.Property<int>("StockUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_unit_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movement");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_stock_movement_created_by_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_stock_movement_customer_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_stock_movement_date");

                    b.HasIndex("StockUnitId")
                        .HasDatabaseName("ix_stock_movement_stock_unit_id");

                    b.ToTable("stock_movement", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.StockUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_stock_unit");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_stock_unit_batch_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stock_unit_status");

                    b.ToTable("stock_unit", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measure");

                    b.HasIndex("Abbreviation")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_of_measure_abbreviation");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_of_measure_label");

                    b.ToTable("unit_of_measure", (string)null);
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.Product", b =>
                {
                    b.HasOne("Butcher.Api.Domain.Entities.UnitOfMeasure", "SaleUnit")
                        .WithMany()
                        .HasForeignKey("SaleUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_units_of_measure_sale_unit_id");

                    b.Navigation("SaleUnit");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.ProductionBatch", b =>
                {
                    b.HasOne("Butcher.Api.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_production_batch_app_user_created_by_id");

                    b.HasOne("Butcher.Api.Domain.Entities.Product", "Product")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_batch_product_product_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Butcher.Api.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_movement_app_user_created_by_id");

                    b.HasOne("Butcher.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("StockMovements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_movement_customer_customer_id");

                    b.HasOne("Butcher.Api.Domain.Entities.StockUnit", "StockUnit")
                        .WithMany("StockMovements")
                        .HasForeignKey("StockUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_stock_units_stock_unit_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");

                    b.Navigation("StockUnit");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.StockUnit", b =>
                {
                    b.HasOne("Butcher.Api.Domain.Entities.ProductionBatch", "Batch")
                        .WithMany("StockUnits")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_unit_production_batch_batch_id");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductionBatches");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.ProductionBatch", b =>
                {
                    b.Navigation("StockUnits");
                });

            modelBuilder.Entity("Butcher.Api.Domain.Entities.StockUnit", b =>
                {
                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
