namespace Butcher.Api.Tests.Application.Assistant;

/// <summary>
/// Transcriptions réelles de l'étape 1 du spike (docs/spike-assistant-vocal.md §7) : une voix,
/// 40 phrases, cinq moteurs. Les enregistrements restent hors de git ; seul le texte est recopié ici.
/// Généré depuis development/assistant-corpus/results/*.csv.
/// </summary>
public static class CorpusTranscripts
{
    public static readonly (string Engine, string PhraseId, string Text)[] All =
    [
        ("voxtral-vocab", "A1", "Il me reste combien de saucissons ?"),
        ("voxtral-vocab", "A2", "Combien j'ai de jambon ?"),
        ("voxtral-vocab", "A3", "Qu'est-ce qu'il reste de terrine ?"),
        ("voxtral-vocab", "A4", "Qu'est-ce qu'il me reste en stock ?"),
        ("voxtral-vocab", "A5", "Il en reste combien du saucisson de la semaine dernière ?"),
        ("voxtral-vocab", "A6", "Le jambon entamé, il en reste combien à peu près ?"),
        ("voxtral-vocab", "A7", "J'ai encore du saucisson."),
        ("voxtral-vocab", "A8", "Dis-moi voir combien il reste de terrine."),
        ("voxtral-vocab", "B1", "Bon, deux saucissons à Madame Martin."),
        ("voxtral-vocab", "B2", "Mais un saucisson pour Martine."),
        ("voxtral-vocab", "B3", "La Josette a pris trois terrines."),
        ("voxtral-vocab", "B4", "Une terrine pour Gérard."),
        ("voxtral-vocab", "B5", "J'ai vendu un saucisson et une terrine au moro."),
        ("voxtral-vocab", "B6", "Paul Lefebvre, de saucisson."),
        ("voxtral-vocab", "B7", "Attends, deux saucissons à Madame Martin."),
        ("voxtral-vocab", "B8", "Vends trois saucissons, non deux, à Madame Martin."),
        ("voxtral-vocab", "C1", "Un saucisson d'environ 300 grammes pour Mme Martin."),
        ("voxtral-vocab", "C2", "Donne un gros saucisson à Gérard."),
        ("voxtral-vocab", "C3", "Un saucisson à 8 euros pour la Josette."),
        ("voxtral-vocab", "C4", "Un saucisson de 350 pour Paul."),
        ("voxtral-vocab", "C5", "un demi kilo de saucisson pour les moraux."),
        ("voxtral-vocab", "D1", "deux cents grammes de jambon pour Mme Barthin."),
        ("voxtral-vocab", "D2", "Coupe 250 grammes de jambon à Gérard."),
        ("voxtral-vocab", "D3", "Une livre de jambon pour les moraux."),
        ("voxtral-vocab", "D4", "4 tranches de jambon pour la Josette."),
        ("voxtral-vocab", "D5", "Un jambon entier pour Paul Lefebvre."),
        ("voxtral-vocab", "E1", "Deux saucissons à Madame Martin, elle a payé."),
        ("voxtral-vocab", "E2", "Une terrine pour Gérard, il payera la semaine prochaine."),
        ("voxtral-vocab", "E3", "Madame Martin a payé en liquide pour ses deux saucissons."),
        ("voxtral-vocab", "E4", "Trois terrines au mot."),
        ("voxtral-vocab", "F1", "Vends deux saucissons à Madame Petitjean."),
        ("voxtral-vocab", "F10", "Combien il reste de saucissons ? Aimez-en deux pour Gérard."),
        ("voxtral-vocab", "F2", "Vends de saucisson."),
        ("voxtral-vocab", "F3", "Vendons quelque chose à Madame Martin."),
        ("voxtral-vocab", "F4", "Madame Martin."),
        ("voxtral-vocab", "F5", "Un petit saucisson à Gérard."),
        ("voxtral-vocab", "F6", "Nous avons deux corisaux à Madame Martin."),
        ("voxtral-vocab", "F7", "Il met des chansons pour enfants."),
        ("voxtral-vocab", "F8", "Annule la dernière vente."),
        ("voxtral-vocab", "F9", "Vends deux saucissons à Madame Martin et une terrine à Gérard."),
        ("voxtral", "A1", "Il me reste combien de saucissons ?"),
        ("voxtral", "A2", "Combien j'ai de jambon ?"),
        ("voxtral", "A3", "Est-ce qu'il reste du terrain ?"),
        ("voxtral", "A4", "Qu'est-ce qu'il me reste en stock ?"),
        ("voxtral", "A5", "Il en reste combien du saucisson de la semaine dernière ?"),
        ("voxtral", "A6", "Le jambon entamé, il en reste combien à peu près ?"),
        ("voxtral", "A7", "J'ai encore du saucisson."),
        ("voxtral", "A8", "Dis-moi voir combien il reste de terrine."),
        ("voxtral", "B1", "Bon, deux saucissons à Madame Martin."),
        ("voxtral", "B2", "Mais un saucisson pour Martine."),
        ("voxtral", "B3", "La Josette a pris trois terrines."),
        ("voxtral", "B4", "Une terrine pour Gérard."),
        ("voxtral", "B5", "J'ai vendu un saucisson et une terrine au Moreau."),
        ("voxtral", "B6", "Paul Lefebvre de Saucisson."),
        ("voxtral", "B7", "Attends, deux saucissons à Madame Martin."),
        ("voxtral", "B8", "Vends trois saucissons, non deux, à Madame Martin."),
        ("voxtral", "C1", "Un saucisson d'environ trois cents grammes pour Mme Martin."),
        ("voxtral", "C2", "Donne un gros saucisson à Gérard."),
        ("voxtral", "C3", "Un saucisson à 8 euros pour la Josette."),
        ("voxtral", "C4", "Un saucisson de 350 pour Paul."),
        ("voxtral", "C5", "Un demi-kilo de saucisson pour les moraux."),
        ("voxtral", "D1", "deux cents grammes de jambon pour Mme Martin."),
        ("voxtral", "D2", "Coupe deux cent cinquante grammes de jambon à Gérard."),
        ("voxtral", "D3", "Une livre de jambon pour les moraux."),
        ("voxtral", "D4", "Quatre tranches de jambon pour la Josette."),
        ("voxtral", "D5", "Un jambon entier pour Paul Lefebvre."),
        ("voxtral", "E1", "Deux saucissons à Madame Martin, elle a payé."),
        ("voxtral", "E2", "Une terrine pour Gérard, il payera la semaine prochaine."),
        ("voxtral", "E3", "Madame Martin a payé en liquide pour ses deux saucissons."),
        ("voxtral", "E4", "Trois terrines au mot."),
        ("voxtral", "F1", "Vends deux saucissons à Madame Petitjean."),
        ("voxtral", "F10", "Combien il reste de saucisson ? Aimez-en deux pour Gérard."),
        ("voxtral", "F2", "Vent de saucisson."),
        ("voxtral", "F3", "Vendons quelque chose à Madame Martin."),
        ("voxtral", "F4", "Madame Martin."),
        ("voxtral", "F5", "Peu anti-saucisson à Gérard."),
        ("voxtral", "F6", "Nous avons deux corisaux à Madame Martin."),
        ("voxtral", "F7", "mais des chansons pour enfants."),
        ("voxtral", "F8", "Annule la dernière vente."),
        ("voxtral", "F9", "Vend deux saucissons à Madame Martin et une terrine à Gérard."),
        ("whisper-medium-vocab", "A1", "il me reste combien de saucissons ?"),
        ("whisper-medium-vocab", "A2", "combien j'ai de jambon"),
        ("whisper-medium-vocab", "A3", "est-ce qu'il reste de terrines ?"),
        ("whisper-medium-vocab", "A4", "qu'est ce qu'il me reste en stock ?"),
        ("whisper-medium-vocab", "A5", "il en reste combien du saucisson de la semaine dernière ?"),
        ("whisper-medium-vocab", "A6", "le jambon entamé il en reste combien à peu près ?"),
        ("whisper-medium-vocab", "A7", "j'ai encore du sauciss... du saucisson"),
        ("whisper-medium-vocab", "A8", "dis-moi voir combien il reste de terrines"),
        ("whisper-medium-vocab", "B1", "bon 2 saucissons à madame martin"),
        ("whisper-medium-vocab", "B2", "meilleurs saucissons pour Martin"),
        ("whisper-medium-vocab", "B3", "la Josette a pris 3 terrines"),
        ("whisper-medium-vocab", "B4", "une terrine projérée"),
        ("whisper-medium-vocab", "B5", "j'ai vendu un saucisson et une terrine au moro"),
        ("whisper-medium-vocab", "B6", "Paul Lefebvre de saucissons"),
        ("whisper-medium-vocab", "B7", "deux saucissons à madame martin"),
        ("whisper-medium-vocab", "B8", "vend 3 saucissons, non 2, à Madame Martin"),
        ("whisper-medium-vocab", "C1", "un saucisson d'environ 300 grammes pour madame martin"),
        ("whisper-medium-vocab", "C2", "donne un gros saucisson à Gérard"),
        ("whisper-medium-vocab", "C3", "saucissons à 8 euros pour la josette"),
        ("whisper-medium-vocab", "C4", "un saucisson de 350 pour l'huile"),
        ("whisper-medium-vocab", "C5", "un demi kilo de saucissons pour les moraux"),
        ("whisper-medium-vocab", "D1", "200 grammes de jambon pour madame Barton"),
        ("whisper-medium-vocab", "D2", "250 grammes de jambon à gérard"),
        ("whisper-medium-vocab", "D3", "une livre de jambon pour les moraux"),
        ("whisper-medium-vocab", "D4", "quatre tranches de jambon pour la josette"),
        ("whisper-medium-vocab", "D5", "un jambon entier pour Paul Lefebvre"),
        ("whisper-medium-vocab", "E1", "deux saucissons à madame martin elle a payé"),
        ("whisper-medium-vocab", "E2", "une terrine pour Gérard, il payera la semaine prochaine"),
        ("whisper-medium-vocab", "E3", "madame martin payé en liquide pour ses saucissons"),
        ("whisper-medium-vocab", "E4", "trois terrines au moraux"),
        ("whisper-medium-vocab", "F1", "vendre de saucissons à madame Petitjot"),
        ("whisper-medium-vocab", "F10", "combien il reste de saucissons émise en deux pour gérard"),
        ("whisper-medium-vocab", "F2", "vendre saucissons"),
        ("whisper-medium-vocab", "F3", "vendre quelque chose à madame martin"),
        ("whisper-medium-vocab", "F4", "Madame Martin"),
        ("whisper-medium-vocab", "F5", "vendu saucissons agérats"),
        ("whisper-medium-vocab", "F6", "vends deux chorizo à madame martin"),
        ("whisper-medium-vocab", "F7", "mets des chansons pour enfants"),
        ("whisper-medium-vocab", "F8", "annule la dernière avance"),
        ("whisper-medium-vocab", "F9", "vend 2 saucissons à madame martin et une terrine à gérard"),
        ("whisper-medium", "A1", "Il me reste combien de saucissons ?"),
        ("whisper-medium", "A2", "Bon, bien, j'ai deux jambons."),
        ("whisper-medium", "A3", "Est-ce qu'il reste de terrain ?"),
        ("whisper-medium", "A4", "Qu'est-ce qu'il me reste en stock ?"),
        ("whisper-medium", "A5", "Il en reste combien du saucisson de la semaine dernière ?"),
        ("whisper-medium", "A6", "Le jambon entamé, il ne reste combien à peu près ?"),
        ("whisper-medium", "A7", "J'ai encore du saucisson."),
        ("whisper-medium", "A8", "Dis-moi voir combien il reste d'Eutérine."),
        ("whisper-medium", "B1", "Bon 2 saucissons à Madame Martin."),
        ("whisper-medium", "B2", "Meilleurs saucissons pour Martin."),
        ("whisper-medium", "B3", "La Josette a pris 3 terrines."),
        ("whisper-medium", "B4", "Une terrine progérée"),
        ("whisper-medium", "B5", "J'ai vendu un saucisson et une terrine aux moraux."),
        ("whisper-medium", "B6", "Paul Lefebvre de Saucisson."),
        ("whisper-medium", "B7", "Attends, d'où ce qu'ils sont ? Madame Martin."),
        ("whisper-medium", "B8", "Vont trois saucissons, non deux, à Madame Martin."),
        ("whisper-medium", "C1", "Un saucisson d'environ 300 grammes pour Madame Martin."),
        ("whisper-medium", "C2", "Donne un gros soucis-son à Gérard."),
        ("whisper-medium", "C3", "Un saucisson à 8 euros pour la Vosette."),
        ("whisper-medium", "C4", "Un saucisson de 350, on call."),
        ("whisper-medium", "C5", "Un demi kilo de saucisson pour les moraux."),
        ("whisper-medium", "D1", "200 grammes de jambon pour Madame Barton."),
        ("whisper-medium", "D2", "250 grammes de jambon à gérard"),
        ("whisper-medium", "D3", "Une livre de jambon pour les moraux."),
        ("whisper-medium", "D4", "Il y a 4 tranches de jambon pour la Josette."),
        ("whisper-medium", "D5", "Un jambon entier pour Paul Lefebvre."),
        ("whisper-medium", "E1", "Deux saucissons à Madame Martin, elle a payé."),
        ("whisper-medium", "E2", "Une terrine pour Gérard, il payera la semaine prochaine."),
        ("whisper-medium", "E3", "Madame Martin a payé en liquide pour ces deux saucissons."),
        ("whisper-medium", "E4", "Trois terrines au morau."),
        ("whisper-medium", "F1", "Le vent de saucissons à Mme Petitjot."),
        ("whisper-medium", "F10", "J'écris bien les restes de saucissons et mets-en deux pour Gérard."),
        ("whisper-medium", "F2", "Bon, deux saucissons."),
        ("whisper-medium", "F3", "On verra quelque chose à Madame Martin."),
        ("whisper-medium", "F4", "Madame Martin."),
        ("whisper-medium", "F5", "On dit saucisson à Gérard."),
        ("whisper-medium", "F6", "Nous avons deux chorizos à Madame Martin."),
        ("whisper-medium", "F7", "Je mets des chansons pour enfants."),
        ("whisper-medium", "F8", "annule la dernière avance."),
        ("whisper-medium", "F9", "On vend deux saucissons à Madame Martin et une terine à Gérard."),
        ("whisper-small", "A1", "Il me reste combien de soucis sont ?"),
        ("whisper-small", "A2", "Combien ? J'ai deux jambons."),
        ("whisper-small", "A3", "Jusqu'il reste du terrain."),
        ("whisper-small", "A4", "Qu'est-ce qu'il me reste en stock ?"),
        ("whisper-small", "A5", "Il le reste combien du saucisson de la semaine dernière ?"),
        ("whisper-small", "A6", "Le jambon ont amé, il ne reste qu'on bien à peu près."),
        ("whisper-small", "A7", "J'ai encore du saucisson."),
        ("whisper-small", "A8", "Dis-moi voir combien il reste de terrain."),
        ("whisper-small", "B1", "Bonne souci, sois-t-on à Mme Marpe."),
        ("whisper-small", "B2", "Mais un soucis sont pour Martin."),
        ("whisper-small", "B3", "La Josette a pris trois terrains."),
        ("whisper-small", "B4", "Une Terrine Prugérat"),
        ("whisper-small", "B5", "J'ai vendu un saucisson et une terrine au moro."),
        ("whisper-small", "B6", "Paul Lefèvre de Saussissons"),
        ("whisper-small", "B7", "Euh... Bon... Attends, deux sous-sissons à Valème Barton."),
        ("whisper-small", "B8", "Vont 3 saucissons, langue 2, à Mme Martin."),
        ("whisper-small", "C1", "Un saucisson d'environ 300 g pour Mme Barton."),
        ("whisper-small", "C2", "Donne un gros souci son à Gérard."),
        ("whisper-small", "C3", "Alors, soucis sont à 8€ pour la Vosette."),
        ("whisper-small", "C4", "un saucisson de 350 pour coller."),
        ("whisper-small", "C5", "Un demi kilo de saucisson pour les moraux."),
        ("whisper-small", "D1", "200 g de jambon pour madame Barton."),
        ("whisper-small", "D2", "Oubles de 150 g de jambon à Gérard"),
        ("whisper-small", "D3", "Une livre de jambons pour les moraux."),
        ("whisper-small", "D4", "4 tronches de jambon pour la josette."),
        ("whisper-small", "D5", "Un jambon hanté pour Paul Lefebvre."),
        ("whisper-small", "E1", "Deux soucis sont à Mme Martin, elle a payé."),
        ("whisper-small", "E2", "Une térine pour Gérard, il payera la semaine prochaine."),
        ("whisper-small", "E3", "Mme Martin payant liquide pour ces deux saucissons."),
        ("whisper-small", "E4", "Trois terrains au mot."),
        ("whisper-small", "F1", "Nous avons deux soucis soins madame Petit Jure."),
        ("whisper-small", "F10", "Combiens les restes de saucisson et mets en deux pour GERA."),
        ("whisper-small", "F2", "Bon, deux soucis sont."),
        ("whisper-small", "F3", "On va voir quelque chose à madame Martin."),
        ("whisper-small", "F4", "Madame Martin."),
        ("whisper-small", "F5", "Vontis, Aussi, Soins, Agéras."),
        ("whisper-small", "F6", "Nous avons deux choriseaux, Mme Martin."),
        ("whisper-small", "F7", "Mets des chansons pour enfants."),
        ("whisper-small", "F8", "annule la dernière avance"),
        ("whisper-small", "F9", "Devant deux saucissons à Mme Martin et une Thérina Gérard."),
    ];
}
