namespace Butcher.Api.Tests.Application.Assistant;

/// <summary>
/// Jeu d'évaluation de la reconnaissance des clients (docs/spike-assistant-vocal.md) :
/// transcriptions réelles de l'étape 1 et phrases écrites (source « ecrit ») pour les noms inconnus.
/// Généré par spikes/assistant-vocal/names/dataset.py : ne pas modifier à la main.
/// </summary>
public static class CorpusTranscripts
{
    public static readonly (string Source, string PhraseId, string Text, int[] Truth, string[] Unknown)[] All =
    [
        ("voxtral-vocab", "A1", "Il me reste combien de saucissons ?", [], []),
        ("voxtral-vocab", "A2", "Combien j'ai de jambon ?", [], []),
        ("voxtral-vocab", "A3", "Qu'est-ce qu'il reste de terrine ?", [], []),
        ("voxtral-vocab", "A4", "Qu'est-ce qu'il me reste en stock ?", [], []),
        ("voxtral-vocab", "A5", "Il en reste combien du saucisson de la semaine dernière ?", [], []),
        ("voxtral-vocab", "A6", "Le jambon entamé, il en reste combien à peu près ?", [], []),
        ("voxtral-vocab", "A7", "J'ai encore du saucisson.", [], []),
        ("voxtral-vocab", "A8", "Dis-moi voir combien il reste de terrine.", [], []),
        ("voxtral-vocab", "B1", "Bon, deux saucissons à Madame Martin.", [1], []),
        ("voxtral-vocab", "B2", "Mais un saucisson pour Martine.", [2], []),
        ("voxtral-vocab", "B3", "La Josette a pris trois terrines.", [3], []),
        ("voxtral-vocab", "B4", "Une terrine pour Gérard.", [6], []),
        ("voxtral-vocab", "B5", "J'ai vendu un saucisson et une terrine au moro.", [5], []),
        ("voxtral-vocab", "B6", "Paul Lefebvre, de saucisson.", [4], []),
        ("voxtral-vocab", "B7", "Attends, deux saucissons à Madame Martin.", [1], []),
        ("voxtral-vocab", "B8", "Vends trois saucissons, non deux, à Madame Martin.", [1], []),
        ("voxtral-vocab", "C1", "Un saucisson d'environ 300 grammes pour Mme Martin.", [1], []),
        ("voxtral-vocab", "C2", "Donne un gros saucisson à Gérard.", [6], []),
        ("voxtral-vocab", "C3", "Un saucisson à 8 euros pour la Josette.", [3], []),
        ("voxtral-vocab", "C4", "Un saucisson de 350 pour Paul.", [4], []),
        ("voxtral-vocab", "C5", "un demi kilo de saucisson pour les moraux.", [5], []),
        ("voxtral-vocab", "D1", "deux cents grammes de jambon pour Mme Barthin.", [1], []),
        ("voxtral-vocab", "D2", "Coupe 250 grammes de jambon à Gérard.", [6], []),
        ("voxtral-vocab", "D3", "Une livre de jambon pour les moraux.", [5], []),
        ("voxtral-vocab", "D4", "4 tranches de jambon pour la Josette.", [3], []),
        ("voxtral-vocab", "D5", "Un jambon entier pour Paul Lefebvre.", [4], []),
        ("voxtral-vocab", "E1", "Deux saucissons à Madame Martin, elle a payé.", [1], []),
        ("voxtral-vocab", "E2", "Une terrine pour Gérard, il payera la semaine prochaine.", [6], []),
        ("voxtral-vocab", "E3", "Madame Martin a payé en liquide pour ses deux saucissons.", [1], []),
        ("voxtral-vocab", "E4", "Trois terrines au mot.", [5], []),
        ("voxtral-vocab", "F1", "Vends deux saucissons à Madame Petitjean.", [], ["Petitjean"]),
        ("voxtral-vocab", "F10", "Combien il reste de saucissons ? Aimez-en deux pour Gérard.", [6], []),
        ("voxtral-vocab", "F2", "Vends de saucisson.", [], []),
        ("voxtral-vocab", "F3", "Vendons quelque chose à Madame Martin.", [1], []),
        ("voxtral-vocab", "F4", "Madame Martin.", [1], []),
        ("voxtral-vocab", "F5", "Un petit saucisson à Gérard.", [6], []),
        ("voxtral-vocab", "F6", "Nous avons deux corisaux à Madame Martin.", [1], []),
        ("voxtral-vocab", "F7", "Il met des chansons pour enfants.", [], []),
        ("voxtral-vocab", "F8", "Annule la dernière vente.", [], []),
        ("voxtral-vocab", "F9", "Vends deux saucissons à Madame Martin et une terrine à Gérard.", [1, 6], []),
        ("voxtral", "A1", "Il me reste combien de saucissons ?", [], []),
        ("voxtral", "A2", "Combien j'ai de jambon ?", [], []),
        ("voxtral", "A3", "Est-ce qu'il reste du terrain ?", [], []),
        ("voxtral", "A4", "Qu'est-ce qu'il me reste en stock ?", [], []),
        ("voxtral", "A5", "Il en reste combien du saucisson de la semaine dernière ?", [], []),
        ("voxtral", "A6", "Le jambon entamé, il en reste combien à peu près ?", [], []),
        ("voxtral", "A7", "J'ai encore du saucisson.", [], []),
        ("voxtral", "A8", "Dis-moi voir combien il reste de terrine.", [], []),
        ("voxtral", "B1", "Bon, deux saucissons à Madame Martin.", [1], []),
        ("voxtral", "B2", "Mais un saucisson pour Martine.", [2], []),
        ("voxtral", "B3", "La Josette a pris trois terrines.", [3], []),
        ("voxtral", "B4", "Une terrine pour Gérard.", [6], []),
        ("voxtral", "B5", "J'ai vendu un saucisson et une terrine au Moreau.", [5], []),
        ("voxtral", "B6", "Paul Lefebvre de Saucisson.", [4], []),
        ("voxtral", "B7", "Attends, deux saucissons à Madame Martin.", [1], []),
        ("voxtral", "B8", "Vends trois saucissons, non deux, à Madame Martin.", [1], []),
        ("voxtral", "C1", "Un saucisson d'environ trois cents grammes pour Mme Martin.", [1], []),
        ("voxtral", "C2", "Donne un gros saucisson à Gérard.", [6], []),
        ("voxtral", "C3", "Un saucisson à 8 euros pour la Josette.", [3], []),
        ("voxtral", "C4", "Un saucisson de 350 pour Paul.", [4], []),
        ("voxtral", "C5", "Un demi-kilo de saucisson pour les moraux.", [5], []),
        ("voxtral", "D1", "deux cents grammes de jambon pour Mme Martin.", [1], []),
        ("voxtral", "D2", "Coupe deux cent cinquante grammes de jambon à Gérard.", [6], []),
        ("voxtral", "D3", "Une livre de jambon pour les moraux.", [5], []),
        ("voxtral", "D4", "Quatre tranches de jambon pour la Josette.", [3], []),
        ("voxtral", "D5", "Un jambon entier pour Paul Lefebvre.", [4], []),
        ("voxtral", "E1", "Deux saucissons à Madame Martin, elle a payé.", [1], []),
        ("voxtral", "E2", "Une terrine pour Gérard, il payera la semaine prochaine.", [6], []),
        ("voxtral", "E3", "Madame Martin a payé en liquide pour ses deux saucissons.", [1], []),
        ("voxtral", "E4", "Trois terrines au mot.", [5], []),
        ("voxtral", "F1", "Vends deux saucissons à Madame Petitjean.", [], ["Petitjean"]),
        ("voxtral", "F10", "Combien il reste de saucisson ? Aimez-en deux pour Gérard.", [6], []),
        ("voxtral", "F2", "Vent de saucisson.", [], []),
        ("voxtral", "F3", "Vendons quelque chose à Madame Martin.", [1], []),
        ("voxtral", "F4", "Madame Martin.", [1], []),
        ("voxtral", "F5", "Peu anti-saucisson à Gérard.", [6], []),
        ("voxtral", "F6", "Nous avons deux corisaux à Madame Martin.", [1], []),
        ("voxtral", "F7", "mais des chansons pour enfants.", [], []),
        ("voxtral", "F8", "Annule la dernière vente.", [], []),
        ("voxtral", "F9", "Vend deux saucissons à Madame Martin et une terrine à Gérard.", [1, 6], []),
        ("whisper-medium-vocab", "A1", "il me reste combien de saucissons ?", [], []),
        ("whisper-medium-vocab", "A2", "combien j'ai de jambon", [], []),
        ("whisper-medium-vocab", "A3", "est-ce qu'il reste de terrines ?", [], []),
        ("whisper-medium-vocab", "A4", "qu'est ce qu'il me reste en stock ?", [], []),
        ("whisper-medium-vocab", "A5", "il en reste combien du saucisson de la semaine dernière ?", [], []),
        ("whisper-medium-vocab", "A6", "le jambon entamé il en reste combien à peu près ?", [], []),
        ("whisper-medium-vocab", "A7", "j'ai encore du sauciss... du saucisson", [], []),
        ("whisper-medium-vocab", "A8", "dis-moi voir combien il reste de terrines", [], []),
        ("whisper-medium-vocab", "B1", "bon 2 saucissons à madame martin", [1], []),
        ("whisper-medium-vocab", "B2", "meilleurs saucissons pour Martin", [2], []),
        ("whisper-medium-vocab", "B3", "la Josette a pris 3 terrines", [3], []),
        ("whisper-medium-vocab", "B4", "une terrine projérée", [6], []),
        ("whisper-medium-vocab", "B5", "j'ai vendu un saucisson et une terrine au moro", [5], []),
        ("whisper-medium-vocab", "B6", "Paul Lefebvre de saucissons", [4], []),
        ("whisper-medium-vocab", "B7", "deux saucissons à madame martin", [1], []),
        ("whisper-medium-vocab", "B8", "vend 3 saucissons, non 2, à Madame Martin", [1], []),
        ("whisper-medium-vocab", "C1", "un saucisson d'environ 300 grammes pour madame martin", [1], []),
        ("whisper-medium-vocab", "C2", "donne un gros saucisson à Gérard", [6], []),
        ("whisper-medium-vocab", "C3", "saucissons à 8 euros pour la josette", [3], []),
        ("whisper-medium-vocab", "C4", "un saucisson de 350 pour l'huile", [4], []),
        ("whisper-medium-vocab", "C5", "un demi kilo de saucissons pour les moraux", [5], []),
        ("whisper-medium-vocab", "D1", "200 grammes de jambon pour madame Barton", [1], []),
        ("whisper-medium-vocab", "D2", "250 grammes de jambon à gérard", [6], []),
        ("whisper-medium-vocab", "D3", "une livre de jambon pour les moraux", [5], []),
        ("whisper-medium-vocab", "D4", "quatre tranches de jambon pour la josette", [3], []),
        ("whisper-medium-vocab", "D5", "un jambon entier pour Paul Lefebvre", [4], []),
        ("whisper-medium-vocab", "E1", "deux saucissons à madame martin elle a payé", [1], []),
        ("whisper-medium-vocab", "E2", "une terrine pour Gérard, il payera la semaine prochaine", [6], []),
        ("whisper-medium-vocab", "E3", "madame martin payé en liquide pour ses saucissons", [1], []),
        ("whisper-medium-vocab", "E4", "trois terrines au moraux", [5], []),
        ("whisper-medium-vocab", "F1", "vendre de saucissons à madame Petitjot", [], ["Petitjean"]),
        ("whisper-medium-vocab", "F10", "combien il reste de saucissons émise en deux pour gérard", [6], []),
        ("whisper-medium-vocab", "F2", "vendre saucissons", [], []),
        ("whisper-medium-vocab", "F3", "vendre quelque chose à madame martin", [1], []),
        ("whisper-medium-vocab", "F4", "Madame Martin", [1], []),
        ("whisper-medium-vocab", "F5", "vendu saucissons agérats", [6], []),
        ("whisper-medium-vocab", "F6", "vends deux chorizo à madame martin", [1], []),
        ("whisper-medium-vocab", "F7", "mets des chansons pour enfants", [], []),
        ("whisper-medium-vocab", "F8", "annule la dernière avance", [], []),
        ("whisper-medium-vocab", "F9", "vend 2 saucissons à madame martin et une terrine à gérard", [1, 6], []),
        ("whisper-medium", "A1", "Il me reste combien de saucissons ?", [], []),
        ("whisper-medium", "A2", "Bon, bien, j'ai deux jambons.", [], []),
        ("whisper-medium", "A3", "Est-ce qu'il reste de terrain ?", [], []),
        ("whisper-medium", "A4", "Qu'est-ce qu'il me reste en stock ?", [], []),
        ("whisper-medium", "A5", "Il en reste combien du saucisson de la semaine dernière ?", [], []),
        ("whisper-medium", "A6", "Le jambon entamé, il ne reste combien à peu près ?", [], []),
        ("whisper-medium", "A7", "J'ai encore du saucisson.", [], []),
        ("whisper-medium", "A8", "Dis-moi voir combien il reste d'Eutérine.", [], []),
        ("whisper-medium", "B1", "Bon 2 saucissons à Madame Martin.", [1], []),
        ("whisper-medium", "B2", "Meilleurs saucissons pour Martin.", [2], []),
        ("whisper-medium", "B3", "La Josette a pris 3 terrines.", [3], []),
        ("whisper-medium", "B4", "Une terrine progérée", [6], []),
        ("whisper-medium", "B5", "J'ai vendu un saucisson et une terrine aux moraux.", [5], []),
        ("whisper-medium", "B6", "Paul Lefebvre de Saucisson.", [4], []),
        ("whisper-medium", "B7", "Attends, d'où ce qu'ils sont ? Madame Martin.", [1], []),
        ("whisper-medium", "B8", "Vont trois saucissons, non deux, à Madame Martin.", [1], []),
        ("whisper-medium", "C1", "Un saucisson d'environ 300 grammes pour Madame Martin.", [1], []),
        ("whisper-medium", "C2", "Donne un gros soucis-son à Gérard.", [6], []),
        ("whisper-medium", "C3", "Un saucisson à 8 euros pour la Vosette.", [3], []),
        ("whisper-medium", "C4", "Un saucisson de 350, on call.", [4], []),
        ("whisper-medium", "C5", "Un demi kilo de saucisson pour les moraux.", [5], []),
        ("whisper-medium", "D1", "200 grammes de jambon pour Madame Barton.", [1], []),
        ("whisper-medium", "D2", "250 grammes de jambon à gérard", [6], []),
        ("whisper-medium", "D3", "Une livre de jambon pour les moraux.", [5], []),
        ("whisper-medium", "D4", "Il y a 4 tranches de jambon pour la Josette.", [3], []),
        ("whisper-medium", "D5", "Un jambon entier pour Paul Lefebvre.", [4], []),
        ("whisper-medium", "E1", "Deux saucissons à Madame Martin, elle a payé.", [1], []),
        ("whisper-medium", "E2", "Une terrine pour Gérard, il payera la semaine prochaine.", [6], []),
        ("whisper-medium", "E3", "Madame Martin a payé en liquide pour ces deux saucissons.", [1], []),
        ("whisper-medium", "E4", "Trois terrines au morau.", [5], []),
        ("whisper-medium", "F1", "Le vent de saucissons à Mme Petitjot.", [], ["Petitjean"]),
        ("whisper-medium", "F10", "J'écris bien les restes de saucissons et mets-en deux pour Gérard.", [6], []),
        ("whisper-medium", "F2", "Bon, deux saucissons.", [], []),
        ("whisper-medium", "F3", "On verra quelque chose à Madame Martin.", [1], []),
        ("whisper-medium", "F4", "Madame Martin.", [1], []),
        ("whisper-medium", "F5", "On dit saucisson à Gérard.", [6], []),
        ("whisper-medium", "F6", "Nous avons deux chorizos à Madame Martin.", [1], []),
        ("whisper-medium", "F7", "Je mets des chansons pour enfants.", [], []),
        ("whisper-medium", "F8", "annule la dernière avance.", [], []),
        ("whisper-medium", "F9", "On vend deux saucissons à Madame Martin et une terine à Gérard.", [1, 6], []),
        ("whisper-small", "A1", "Il me reste combien de soucis sont ?", [], []),
        ("whisper-small", "A2", "Combien ? J'ai deux jambons.", [], []),
        ("whisper-small", "A3", "Jusqu'il reste du terrain.", [], []),
        ("whisper-small", "A4", "Qu'est-ce qu'il me reste en stock ?", [], []),
        ("whisper-small", "A5", "Il le reste combien du saucisson de la semaine dernière ?", [], []),
        ("whisper-small", "A6", "Le jambon ont amé, il ne reste qu'on bien à peu près.", [], []),
        ("whisper-small", "A7", "J'ai encore du saucisson.", [], []),
        ("whisper-small", "A8", "Dis-moi voir combien il reste de terrain.", [], []),
        ("whisper-small", "B1", "Bonne souci, sois-t-on à Mme Marpe.", [1], []),
        ("whisper-small", "B2", "Mais un soucis sont pour Martin.", [2], []),
        ("whisper-small", "B3", "La Josette a pris trois terrains.", [3], []),
        ("whisper-small", "B4", "Une Terrine Prugérat", [6], []),
        ("whisper-small", "B5", "J'ai vendu un saucisson et une terrine au moro.", [5], []),
        ("whisper-small", "B6", "Paul Lefèvre de Saussissons", [4], []),
        ("whisper-small", "B7", "Euh... Bon... Attends, deux sous-sissons à Valème Barton.", [1], []),
        ("whisper-small", "B8", "Vont 3 saucissons, langue 2, à Mme Martin.", [1], []),
        ("whisper-small", "C1", "Un saucisson d'environ 300 g pour Mme Barton.", [1], []),
        ("whisper-small", "C2", "Donne un gros souci son à Gérard.", [6], []),
        ("whisper-small", "C3", "Alors, soucis sont à 8€ pour la Vosette.", [3], []),
        ("whisper-small", "C4", "un saucisson de 350 pour coller.", [4], []),
        ("whisper-small", "C5", "Un demi kilo de saucisson pour les moraux.", [5], []),
        ("whisper-small", "D1", "200 g de jambon pour madame Barton.", [1], []),
        ("whisper-small", "D2", "Oubles de 150 g de jambon à Gérard", [6], []),
        ("whisper-small", "D3", "Une livre de jambons pour les moraux.", [5], []),
        ("whisper-small", "D4", "4 tronches de jambon pour la josette.", [3], []),
        ("whisper-small", "D5", "Un jambon hanté pour Paul Lefebvre.", [4], []),
        ("whisper-small", "E1", "Deux soucis sont à Mme Martin, elle a payé.", [1], []),
        ("whisper-small", "E2", "Une térine pour Gérard, il payera la semaine prochaine.", [6], []),
        ("whisper-small", "E3", "Mme Martin payant liquide pour ces deux saucissons.", [1], []),
        ("whisper-small", "E4", "Trois terrains au mot.", [5], []),
        ("whisper-small", "F1", "Nous avons deux soucis soins madame Petit Jure.", [], ["Petitjean"]),
        ("whisper-small", "F10", "Combiens les restes de saucisson et mets en deux pour GERA.", [6], []),
        ("whisper-small", "F2", "Bon, deux soucis sont.", [], []),
        ("whisper-small", "F3", "On va voir quelque chose à madame Martin.", [1], []),
        ("whisper-small", "F4", "Madame Martin.", [1], []),
        ("whisper-small", "F5", "Vontis, Aussi, Soins, Agéras.", [6], []),
        ("whisper-small", "F6", "Nous avons deux choriseaux, Mme Martin.", [1], []),
        ("whisper-small", "F7", "Mets des chansons pour enfants.", [], []),
        ("whisper-small", "F8", "annule la dernière avance", [], []),
        ("whisper-small", "F9", "Devant deux saucissons à Mme Martin et une Thérina Gérard.", [1, 6], []),
        ("ecrit", "X1", "Deux saucissons pour Madame Lambert.", [], ["Lambert"]),
        ("ecrit", "X2", "deux saucissons pour madame lambert", [], ["lambert"]),
        ("ecrit", "X3", "Une terrine pour Jean-Pierre.", [], ["Jean", "Pierre"]),
        ("ecrit", "X4", "une terrine pour jean-pierre", [], ["jean", "pierre"]),
        ("ecrit", "X5", "Mets un jambon pour les Dupont.", [], ["Dupont"]),
        ("ecrit", "X6", "mets un jambon pour les dupont", [], ["dupont"]),
        ("ecrit", "X7", "Vends trois saucissons à Bernadette.", [], ["Bernadette"]),
        ("ecrit", "X8", "vends trois saucissons à bernadette", [], ["bernadette"]),
        ("ecrit", "X9", "Un saucisson pour Monsieur Garcia, il a payé.", [], ["Garcia"]),
        ("ecrit", "X10", "Deux saucissons pour la Simone.", [], ["Simone"]),
        ("ecrit", "X11", "Mets deux saucissons pour Gérard et un pour Madame Lambert.", [6], ["Lambert"]),
        ("ecrit", "X12", "Une livre de jambon pour Paul.", [4], []),
        ("ecrit", "X13", "Combien il reste de saucissons pour Noël ?", [], []),
        ("ecrit", "X14", "Un saucisson pour Pâques.", [], []),
        ("ecrit", "X15", "Deux terrines pour demain.", [], []),
        ("ecrit", "X16", "Un jambon pour la fête du village.", [], []),
    ];
}
